"""Default node capacities from the assignment specification."""

NODE_SIZE_BYTES = 1024
LEAF_ENTRY_SIZE_BYTES = 20
INTERNAL_ENTRY_SIZE_BYTES = 36
MINIMUM_FILL_RATIO = 0.40

LEAF_MAX_ENTRIES = NODE_SIZE_BYTES // LEAF_ENTRY_SIZE_BYTES  # 51
LEAF_MIN_ENTRIES = int(LEAF_MAX_ENTRIES * MINIMUM_FILL_RATIO)  # 20
INTERNAL_MAX_ENTRIES = NODE_SIZE_BYTES // INTERNAL_ENTRY_SIZE_BYTES  # 28
INTERNAL_MIN_ENTRIES = int(INTERNAL_MAX_ENTRIES * MINIMUM_FILL_RATIO)  # 11
